# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

dist: trusty

matrix:
    include:
        # Longest build first
        # Parametrize the conda env name so multiple builds can
        # work with multiple environments on the same machine in parallel.
        - os: osx
          env: PYTHON=3.6 NUMPY=1.12 BUILD_DOC=yes CONDA_ENV=travisci
        - env: PYTHON=3.5 NUMPY=1.11 RUN_COVERAGE=yes CONDA_ENV=travisci
        - env: PYTHON=3.6 NUMPY=1.12 BUILD_DOC=yes CONDA_ENV=travisci
        - env: PYTHON=3.6 NUMPY=1.13 CONDA_ENV=travisci
        - env: PYTHON=3.6 NUMPY=1.14 CONDA_ENV=travisci
        - env: PYTHON=3.6 NUMPY=1.14 CONDA_ENV=travisci TEST_SVML=yes
        - env: PYTHON=3.5 NUMPY=1.10 CONDA_ENV=travisci
        - env: PYTHON=2.7 NUMPY=1.9 CONDA_ENV=travisci
        - env: PYTHON=2.7 NUMPY=1.14 CONDA_ENV=travisci
        - env: PYTHON=3.7 NUMPY=1.14 CONDA_ENV=travisci USE_C3I_TEST_CHANNEL=yes

before_install:
    - buildscripts/incremental/install_miniconda.sh
    - export PATH=$HOME/miniconda3/bin:$PATH
    - buildscripts/incremental/setup_conda_environment.sh
install:
    - buildscripts/incremental/build.sh

script:
    - buildscripts/incremental/test.sh

after_success:
    - buildscripts/incremental/after_success.sh

notifications:
    email: false
    on_success: "change"
    on_failure: "always" # "change"
    slack:
        secure: SGgsT4DevPiF/u4y3HBorUYCVWan7EjSnEBmuGPnGkepv8JxfOnbbeM3ca2TSWa601J4OP2K2JhehUGZSn6YkTx5XKOzqF2pddZQX8j0B4htDgV2qvcY/aIUFz8UW2uQAuguP6OlHPmAj5KgF5raJ34rkmTd8UgObL6jAan2Kzg=
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/bd67cc227432d99bf1f1
        on_success: change
        on_failure: always
        on_start: false
